### ISSUE TITLE
Typescript usage

### ISSUE THREAD

**Issue by uautkarsh** [rotaready/moment-range#120]
Hello,

I am trying to use `moment-range` in [Angular 2 seed by mgechev](https://github.com/mgechev/angular2-seed).

The Angular 2 seed uses typescript, and after several tries, I was not able to use it there. I am not sure if I am missing something.

Can I use `moment-range` in typescript? If yes, then how do I use it? Otherwise, would it be supported with typescript anytime soon?

Thank You

**Comment by maxailloud** [comment]
Usin moment-range typescript definition https://www.nuget.org/packages/moment-range.TypeScript.DefinitelyTyped/ and including moment-range into the angular-cli.json file for a project managed by Angular-cli seems to make it work, but it's really not a nice solution.

**Comment by gf3** [comment]
i would love to include this in the project officially, @maxailloud 

i've also been adding flow typing in the upcoming v3 release, [example here](https://github.com/gf3/moment-range/blob/f6517c606e2216805b7552577ab741e08b97a516/lib/moment-range.js#L51)

**Comment by maxailloud** [comment]
Yeah sure @gf3 go ahead.
Maybe just don't forget to make the PR to remove the typing definitions from https://github.com/DefinitelyTyped/DefinitelyTyped if you do, https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package to help on the process to do so.

**Comment by Gideonnn** [comment]
@uautkarsh Did you find a solution? I have the same problem right now. I do have the @types and added it with `addPackagesBundles`, but it still does not work.

**Comment by gf3** [comment]
@Gideonnn i'm planning on adding typescript definitions to moment-range, however i might need a little help with it as i don't have a ton of experience with typescript

**Comment by uautkarsh** [comment]
@Gideonnn I did not. I gave up due to time constraints.

@gf3 I am no expert either, but I am willing to help you with it. We can figure out how to add it.

**Comment by Syam** [comment]
Same challenge for me : trying to make this plugin working with angular2 with no chance until now.

i also tried the DefinitelyTyped definitions :
```
import * as moment from 'moment';
import 'moment-range';

console.log(moment.range(date1, date2));
```

got error
```
moment.range is not a function
```

I tried this
```
import * as moment from 'moment-range';

console.log(moment);
```
It seem a correct object, but can't call any function on it.
```
Object
DateRange
:
DateRange(start, end)
__esModule
:
true
extendMoment
:
extendMoment(moment)
__proto__
:
Object
```

**Comment by Syam** [comment]
I added this line to index.d.ts from DefinitelyTyped moment-range
```
function extendMoment(moment:any):any;
```

Then it works like this
```
import * as moment from 'moment';
import { extendMoment } from 'moment-range';

let DateRange = extendMoment(moment);

let range:Date[] = new DateRange.range(date1, date2).by('days');
console.log(rangeDate)
```
This is not a convenient way, but I don't find how to to apply or call the extendMoment() function automatically from a module import.

Any idea ?

**Comment by Syam** [comment]
Finally found a good working way (DefinitelyTyped definitions required)

lib/moment-extended.ts
```
import * as moment from 'moment';
import { extendMoment, Range } from 'moment-range';


declare module 'moment' {
    function extendMoment(moment:any): any;

    interface Moment {
        (inp?: moment.MomentInput, format?: moment.MomentFormatSpecification, strict?: boolean): moment.Moment;
        (inp?: moment.MomentInput, format?: moment.MomentFormatSpecification, language?: string, strict?: boolean): moment.Moment;

        range(start: Date, end: Date): Range;
        range(start: Moment, end: Moment): Range;
        range(range: Date[]): Range;
        range(range: Moment[]): Range;
        range(range: string): Range;
    }

    interface Range {
        by (range: string, hollaback?: (current: Moment) => void, exclusive?: boolean): Date[];
        by (range: Range, hollaback?: (current: Moment) => void, exclusive?: boolean): Date[];
    }
}

const Extended:moment.Moment = extendMoment(moment);

export = Extended;
```

Usage
```
import * as moment from 'moment-extended';

let range:Date[] = moment.range(date1, date2).by('days');
```

I guess i would be able to commit a native moment-range.ts definition file soon for moment-range.

**Comment by depl0y** [comment]
Is this still valid? I have implemented the solution @Syam provided, but the `by` method returns an empty array for me. It seems that maybe the typings are out of date?

**Comment by gf3** [comment]
the typings are almost certainly out of date. the API has changed in the latest release—i wish i could be of more help here, however i don't have much experience with TypeScript

the [flow.js declarations](https://github.com/gf3/moment-range/blob/master/declarations/moment-range.js.flow) are current and may be helpful for generating the matching TS definitions

**Comment by ezequielzacca** [comment]
is this fixed? i cannot make this work using Typescript

**Comment by chakrachi** [comment]
also having trouble implementing with Typescript at the moment..

**Comment by elvnthaus** [comment]
Would also love to use this in angular2+

**Comment by junior-ales** [comment]
I'm using the [@types/moment-range](https://www.npmjs.com/package/@types/moment-range) definitions and only the `range` function from `moment-range`. A bit hacky as I don't use the enhanced moment object for all the other moment functions but it's working so far.

```typescript
import * as moment from 'moment';
import { extendMoment } from 'moment-range';

const { range } = extendMoment(moment);

const timeRange = range(moment.utc([2015, 0, 1]), moment.utc([2015, 5, 1]));

for (const month of timeRange.by('month')) {
   console.log(month.format('YYYY-MM-DD'));
}
```

**Comment by gf3** [comment]
i've just [opened a PR](https://github.com/rotaready/moment-range/pull/204) to add typescript definitions to moment-range—it should cover everything!

**Comment by gf3** [comment]
Closed by #204

**Comment by ingarpo** [comment]
Use diff from Moment.

**Comment by gf3** [comment]
@ingarpo can you give `4.0.0` a shot? it should fix the typescript issues

**Comment by ssamuels0916** [comment]
@gf3 Is there updated documentation on how to get the range working in a typescript file? I added the definedTypes plugin for typescript and I downloaded version 4.0.0 but it still skips the range method in my typescript file.
 Thank you

**Comment by gf3** [comment]
i can look into this more next week, but everything should Just Work™ with 4.0.0

**Comment by chason** [comment]
I'm still getting the `moment is not a function` error in TypeScript. I'm using moment-range 4.0.2
